name: PECL

on:
  push:
    tags:
      - '*'

jobs:
  PublishAssets:
    name: Build and publish assets (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        php:
          - 8.2
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Fetch libui-ng
        run: git submodule update --init
      - name: Build package
        run: pecl package package.xml
      - name: Tryout package
        run: |
          sudo python3 -m pip install --upgrade pip setuptools wheel
          sudo pip3 install meson ninja
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev xvfb
          sudo pecl install ardillo-*.tgz
      - name: Check for PHP startup warnings
        run: |
          xvfb-run php -d display_errors=stderr -d display_startup_errors=1 -d error_reporting=-1 -r ';' 2>/tmp/php-startup-warnings
          if [ -s /tmp/php-startup-warnings ]; then
            echo 'The PHP extension was successfully installed, but PHP raised these warnings:' >&2
            cat /tmp/php-startup-warnings >&2
            exit 1
          fi
          echo "PHP didn't raise any warnings at startup."
      - name: Inspect extension
        run: xvfb-run php --ri ardillo
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ardillo-*.tgz
          file_glob: true
          tag: ${{ github.ref }}
          prerelease: true
          overwrite: true
